- name: Deploy /etc/systemd/system/sui.service
  become: true
  template:
    src: 'sui.service.j2'
    dest: '/etc/systemd/system/sui.service'
    owner: "{{ sui_user }}"
    group: "{{ sui_user }}"
    mode: '0644'
  notify: daemon-reload

- name: Enable and start sui service
  become: true
  systemd:
    name: sui.service
    enabled: yes
    state: started
    daemon_reload: yes